AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'app/lib/spellcheck/content.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
